config/routes.rb
Rails.application.routes.draw do
  # simplify devise path names and change sign_in/sign_out to login/logout
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  resources :products do
    resources :comments
  end
  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  post 'simple_pages/thank_you'
  post 'payments/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'simple_pages#landing_page'

  mount ActionCable.server => '/cable'

end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  # include SimplePagesHelper

  def index
  end

  def landing_page
    @products = Product.limit(4)
    # @products = get_featured_products
  end

  def before_landing
    render layout: "landing_layout"
  end

  def contact
  end

  def thank_you
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    ActionMailer::Base.mail(from: @email,
      to: 'spam@mylu.de',
      subject: "A new contact form message from #{@name}",
      body: @message).deliver_now
  end

end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
  # def get_featured_products
  #   featured_products = $redis.get("featured_products")
  #   if featured_products.nil?
  #     featured_products = Product.limit(4).to_json
  #     $redis.set("featured_products", featured_products)
  #     $redis.expire("featured_products",1.hour.to_i)
  #   end
  #   JSON.load featured_products
  # end
end

app/views/simple_pages/about.html.erb
<h1>About this page</h1>

<div class="my-svg-wrapper">
  <svg viewBox="0 0 280 280" style="background-color:#ffffff00" xmlns="http://www.w3.org/2000/svg" width="280" height="280">
    <g stroke="#FFF" stroke-width="1" fill="none">

      <path d="M253.52,142.729c-3.911-1.2-7.846-2.335-11.774-3.489c-7.163-31.434-16.923-60.373-6.613-92.384
      c6.454-4.553,12.909-9.1,19.379-13.601c1.942-1.351,0.093-4.562-1.869-3.197c-5.803,4.038-11.692,8.011-17.536,12.018
      c0.016-0.477-0.189-0.945-0.759-1.024c-22.926-3.165-55.577-7.334-71.604-25.694c-0.228-0.261-0.478-0.393-0.732-0.473
      c1.293-4.142,2.562-8.291,3.945-12.411c0.828-2.469-3.091-3.543-3.899-1.075c-1.324,4.047-2.565,8.123-3.823,12.193
      c-24.118,6.544-51.104,16.03-75.467,6.431c-3.754-6.33-7.529-12.644-11.373-18.909c-0.824-1.344-2.793-0.166-2.098,1.227
      c3.11,6.237,6.299,12.441,9.501,18.64C68.562,31.18,59.952,43.264,50.139,53.896C39.935,64.952,27.36,81.683,11.774,83.94
      c-0.559,0.081-0.868,0.445-1.052,0.877c-0.099,0.056-0.167,0.126-0.228,0.224c-1.755-0.369-3.519-0.738-5.27-1.106
      c-1.437-0.302-2.035,1.786-0.61,2.212c1.944,0.581,3.9,1.118,5.848,1.684c1.505,36.632,9.031,69.116,2.487,106.287
      c-0.162,0.92,0.355,1.594,1.021,1.922c-0.546,0.545-0.705,1.533,0.141,1.903c30.819,13.477,66.689,16.668,88.694,44.769
      c-1.144,5.114-2.248,10.255-3.412,15.355c-0.247,1.084,1.328,1.52,1.665,0.459c1.42-4.479,2.694-8.996,4.022-13.499
      c0.734,0.248,1.562,0.014,2.073-0.471c16.824-2.423,32.945-6.865,50.113-7.295c13.538-0.34,34.345-1.279,45.561,7.964
      c0.884,1.59,1.783,3.176,2.664,4.767c1.382,2.493,5.21,0.262,3.825-2.236c-5.725-10.32-11.36-20.74-17.033-31.117
      c0.046-0.049,0.116-0.053,0.151-0.119c14.252-26.672,30.488-49.63,50.003-72.66c3.331,0.941,6.671,1.85,9.992,2.833
      C254.972,147.446,256.045,143.503,253.52,142.729z M239.009,138.429c-7.767-2.26-15.552-4.471-23.365-6.607
      c-6.55-21.891-14.178-42.222-8.337-65.231c7.563-5.392,15.128-10.772,22.7-16.129C221.959,79.452,228.152,110.686,239.009,138.429z
      M71.5,103.696c6.294,1.479,12.593,2.937,18.901,4.362c-0.791,11.407-0.951,22.868-1.668,34.283
      c-7.395,5.211-14.692,10.533-22.025,15.815C72.162,140.416,74.06,122.133,71.5,103.696z M75.465,98.684
      c11.193-7.231,22.708-17.619,28.77-29.557c2.222,4.103,4.386,8.231,6.626,12.325c-7.185,6.025-13.477,13.145-19.028,20.694
      C86.377,100.973,80.922,99.841,75.465,98.684z M132.825,107.604c-4.73-8.579-9.488-17.14-14.275-25.682
      c7.003,0.032,14.027-0.446,20.943-1.572C137.204,89.414,134.985,98.501,132.825,107.604z M134.385,123.893
      c3.41,6.075,6.844,12.137,10.27,18.203c-2.257,0.032-4.586,0.428-6.718,0.649c-2.622,0.272-5.248,0.563-7.864,0.909
      C131.51,137.068,132.944,130.48,134.385,123.893z M126.489,109.747c-10.266-2.31-20.544-4.566-30.828-6.786
      c5.093-6.769,10.651-13.033,16.467-19.185C116.882,92.448,121.672,101.104,126.489,109.747z M126.491,116.059
      c-6.323,4.338-12.614,8.716-18.911,13.086c2.095-5.181,4.203-10.622,5.645-15.99C117.646,114.125,122.068,115.093,126.491,116.059z
      M129.426,122.067c-1.415,6.131-2.767,12.278-4.145,18.419c-2.452-1.973-5.678-3.325-8.379-4.653
      c-1.427-0.701-2.882-1.341-4.34-1.973C118.186,129.933,123.819,126.022,129.426,122.067z M129.517,146.192
      c3.326,0.035,6.668-0.039,9.986-0.162c2.376-0.088,4.812,0.037,7.101-0.479c2.695,4.767,5.395,9.523,8.094,14.287
      c-9.687,0.753-19.553,1.713-29.054,3.898C126.947,157.891,128.238,152.044,129.517,146.192z M138.984,118.79
      c8.79,1.922,17.577,3.863,26.355,5.835c-3.11,2.341-5.893,5.32-8.548,8.063c-2.231,2.306-4.321,4.721-6.334,7.203
      C146.63,132.857,142.835,125.811,138.984,118.79z M141.863,113.287c7.485-5.312,14.952-10.647,22.42-15.981
      c0.619,7.473,1.854,15.043,3.926,22.237C159.442,117.409,150.66,115.32,141.863,113.287z M164.019,90.498
      c-6.661-3.491-13.164-7.106-19.54-11.152c1.092-4.591,2.238-9.168,3.379-13.747c8.34,6.541,18.585,13.161,28.969,16.223
      C172.554,84.713,168.292,87.604,164.019,90.498z M161.235,92.389c-7.806,5.29-15.613,10.58-23.404,15.895
      c1.886-8.472,3.812-16.934,5.801-25.381C149.077,86.687,155.036,89.924,161.235,92.389z M140.111,77.991
      c-7.832,0.212-15.654,0.463-23.493,0.501c-2.082-3.705-4.228-7.366-6.324-11.062c11.135,0.909,22.969,0.037,33.535-3.694
      C142.575,68.483,141.321,73.23,140.111,77.991z M92.569,108.544c5.976,1.345,11.95,2.696,17.934,4.013
      c-3.267,5.821-5.694,12.804-7.413,18.91c-0.085,0.303-0.08,0.567-0.034,0.808c-3.652,2.543-7.279,5.117-10.919,7.674
      C92.803,129.513,93.235,118.981,92.569,108.544z M109.754,135.823c2.074,1.033,4.172,2.019,6.212,3.123
      c2.791,1.511,5.586,3.606,8.615,4.655c-1.272,5.693-2.488,11.391-3.74,17.088c-8.459-5.268-17.546-9.814-26.501-14.224
      C99.482,142.926,104.629,139.394,109.754,135.823z M125.155,165.919c9.983-0.441,19.958-1.645,29.925-2.342
      c0.599-0.042,1.048-0.308,1.35-0.681c4.082,7.202,8.154,14.4,12.234,21.599c-9.011-2.237-18.345-2.809-27.574-1.628
      c-6.002,0.768-15.008,2.04-21.09,5.548C121.762,180.928,123.476,173.428,125.155,165.919z M151.808,142.372
      c2.401-2.489,4.782-4.998,7.281-7.388c3.294-3.149,7.167-5.903,10.206-9.279c0.046-0.051,0.062-0.11,0.1-0.163
      c4.038,0.913,8.068,1.862,12.101,2.796c-4.346,3.894-8.002,8.839-11.502,13.375c-3.725,4.828-7.256,9.869-10.31,15.161
      C157.058,152.039,154.437,147.206,151.808,142.372z M170.779,120.165c-0.948-8.412-2.156-16.81-3.195-25.212
      c4.096-2.927,8.186-5.846,12.279-8.774c1.629,12.467,2.781,25.042,4.755,37.455C180.008,122.469,175.4,121.296,170.779,120.165z
      M179.755,79.838c-4.872-2.559-10.066-4.623-14.847-7.34c-5.636-3.203-10.902-6.863-16.124-10.668
      c0.027-0.105,0.055-0.209,0.082-0.314c0.058-0.103,0.085-0.198,0.082-0.313c1.39-5.489,2.832-10.965,4.312-16.432
      c5.416,7.006,15.163,11.558,22.583,15.123c7.913,3.802,16.205,6.175,24.756,5.808C193.65,70.414,186.712,75.131,179.755,79.838z
      M144.596,60.798c-12.315,1.872-24.047,3.31-36.588,2.632c-2.851-5.011-5.759-9.982-8.634-14.977
      c5.82,1.856,11.991,1.517,18.375,0.639c11.035-1.516,22.657-3.54,32.577-8.84C148.383,47.09,146.427,53.924,144.596,60.798z
      M102.82,66.495c-4.115,5.314-7.829,10.896-12.589,15.762c-5.883,6.014-12.538,10.967-19.648,15.395
      c-8.742-1.847-17.447-3.663-26.18-5.494C65.7,85.24,84.273,69.834,93.752,49.485C96.774,55.155,99.763,60.839,102.82,66.495z
      M69.251,103.178c1.196,20.011-0.784,39.295-7.319,58.408c-7.792,5.644-15.554,11.322-23.264,17.057
      c7.334-26.641,7.049-55.801,1.036-82.771C49.526,98.413,59.375,100.845,69.251,103.178z M67.564,164.633
      c7.26,2.816,14.793,4.853,21.943,7.965c9.552,4.157,17.567,10.199,24.925,17.465c-1.126,5.173-2.261,10.337-3.389,15.507
      c-17.747-15.804-45.92-22.18-69.475-23.808C50.273,176.127,58.936,170.412,67.564,164.633z M69.751,163.175
      c7.529-5.056,15.041-10.144,22.524-15.285c9.024,5.696,18.255,11.505,27.82,16.203c-1.596,7.282-3.177,14.557-4.762,21.838
      C102.275,172.994,86.751,168.573,69.751,163.175z M119.158,191.907c4.321-3.598,21.815-5.377,24.15-5.582
      c8.638-0.76,16.874,0.142,25.388,1.747c0.721,0.136,1.288-0.141,1.672-0.569c5.237,9.242,10.462,18.486,15.672,27.732
      c-21.125-12.244-47.843-14.128-70.928-6.761C116.496,202.96,117.843,197.438,119.158,191.907z M161.033,159.361
      c4.202-5.74,8.259-11.554,12.765-17.074c3.621-4.436,7.927-8.48,11.275-13.122c8.039,1.878,16.059,3.831,24.067,5.83
      c-17.627,8.8-28.685,28.499-36.108,46.453C169.033,174.084,165.031,166.728,161.033,159.361z M187.185,124.278
      c0.099-13.526-1.803-27.174-3.958-40.503c6.579-4.706,13.159-9.39,19.737-14.085c-4.493,20.872,1.394,42.036,9.906,61.397
      C204.325,128.769,195.777,126.462,187.185,124.278z M160.903,18.376c15.701,18.064,48.809,24.031,71.766,24.808
      c-0.211,0.196-0.46,0.336-0.577,0.663c-0.045,0.126-0.077,0.254-0.122,0.38c-9.288,6.369-18.537,12.766-27.871,19.102
      c-9.923-0.322-18.959-2.767-27.94-7.448c-7.233-3.77-17.263-8.526-21.584-15.849C156.578,32.786,158.7,25.571,160.903,18.376z
      M157.373,16.34c-2.182,7.142-4.307,14.303-6.361,21.488c-16.129,5.12-38.106,13.052-54.377,5.876
      c-3.616-6.253-7.259-12.486-10.922-18.705C107.61,32.764,136.766,25.708,157.373,16.34z M46.183,63.561
      C57.971,51.208,71.136,37.822,79.729,22.81c4.195,8.099,8.439,16.177,12.724,24.238C80.022,68.32,62.178,83.51,38.121,90.392
      c-0.188-0.022-0.373,0.023-0.494,0.163c-0.074,0.021-0.14,0.051-0.214,0.071c-0.036,0.01-0.055,0.033-0.089,0.045
      c-6.689-1.401-13.372-2.806-20.059-4.21C29.151,83.091,37.841,72.303,46.183,63.561z M15.743,195.918
      c0.24-0.202,0.44-0.472,0.514-0.887c6.24-34.886,5.11-72.065-3.637-106.577c8.354,2.407,16.729,4.731,25.14,6.924
      c1.743,29.555,5.102,56.963-3.3,86.321c-0.015,0.051-0.001,0.093-0.012,0.143c-6.229,4.666-12.438,9.353-18.578,14.117
      C15.829,195.944,15.785,195.931,15.743,195.918z M18.079,196.65c7.041-4.379,14.046-8.825,21.024-13.325
      c24.579,7.586,51.351,7.523,71.05,26.325c-2.085,9.543-4.229,19.044-6.347,28.563C82.424,213.169,48.578,206.203,18.079,196.65z
      M199.175,238.695c-9.346-4.557-23.851-5.023-31.954-5.314c-10.953-0.393-22.015,0.244-32.874,1.731
      c-3.427,0.47-6.78,0.995-10.173,1.712c-6.07,1.281-11.307,5.034-16.546,6.636c0.657-0.201,0.682-1.168,0-1.358
      c-0.365-0.102-0.616-0.164-0.867-0.217c-0.185-0.222-0.368-0.447-0.546-0.678c2.868-9.916,5.612-19.864,8.151-29.864
      c26.405-6.326,49.366-2.733,73.766,8.682c0.241,0.113,0.472,0.154,0.693,0.157C192.297,226.351,195.73,232.524,199.175,238.695z
      M191.271,214.794c-5.495-10.057-11.029-20.068-16.504-30.15c8.845-18.705,19.764-39.468,39.43-47.969
      c0.177-0.076,0.299-0.192,0.42-0.307c8.173,2.078,16.317,4.272,24.444,6.535C218.481,162.384,201.504,188.52,191.271,214.794z"/>
    </g>
  </svg>
</div>

<div class = "hidden" id = "myAboutText">
  This app is about selling cobwebs. Yes, that does not make much sense.
</div>

app/views/simple_pages/before_landing.html.erb
<p id="notice"><%= notice %></p>
<%= link_to(image_tag("cobweb.svg", :class => "my-before-landing-image", :id => "mySpin"), simple_pages_landing_page_path, class: "my-before-landing")%>

app/views/simple_pages/contact.html.erb
<% cache do %>
  <% sleep 2 %>
  <h1>Contact Us</h1>
<% end %>


<%= flash[:notice] %>

<%= form_with(url:"/simple_pages/thank_you", method: "post", local: true) do |form| %>
<div class="row">
  <div class="form-group col-md-6">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control", placeholder: "Enter Name", required: true %>
  </div>
</div>

<div class="row">
  <div class="form-group col-md-6 ">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control", placeholder: "Enter Email", required: true %>
  </div>
</div>

<div class="row">
  <div class="form-group col-md-6 ">
    <%= form.label :message %>
    <%= form.text_area :message, class: "form-control", placeholder: "Enter Message", rows: 5, required: true %>
  </div>
</div>

<div class="row">
  <%= form.submit "Send", class: "form_label btn btn-light my-margin-left", id: "myContactSendBtn" %>
</div>

<% end %>

app/views/simple_pages/index.html.erb
<div class = "my-main-content">
  <h1>Welcome to this dummy website!</h1>
  <h2>Home of ruby mystery and rails magic</h2>

  <div class = "my-col-wrapper">

    <div class = "my-columns">
      <%= image_tag("mask.png", class: "img-responsive my-image") %>
      <div class = "my-center"><em> Lorem ipsum</em></div>
      <br>
      <p>Dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor, invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>
    </div>

    <div class = "my-columns">
      <h3>Some h3 text</h3>
      Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
      <br>
      Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
    </div>

    <div class = "my-columns">
      <h3>Some more h3 text</h3>
      Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
    </div>

  </div>

  <div class = "my-float-clearer"></div>

</div>

app/views/simple_pages/landing_page.html.erb
<div class = "row my-column-wrapper">

  <div class = "col-sm-12 col-md-4 my-intro-text">
    <h1>Best Cobwebs</h1>
    <p>Here at <em>The Cobweb Company</em> we serve only the finest and most delicate cobwebs from all over the world! </p>
    <p>
      From the large web of the deadly klingon cave crawler to the fragile net of the tiny paramecium spider, we have them all. Moreover, instead of presenting meaningless Lorem ipsum text, we share wisdom and beauty.
    </p>
  </div> <!-- end  column-->

  <div class = "col-sm-12 col-md-4 my-intro-text">
    <h1>Best Service</h1>
    <p> We keep your cobwebs fresh and shiny! Because we care and we can!</p>
    <p> If your cobwebs are sticky or broken, mail them in and we will send you a quote at no additional costs! All of our cobwebs come with full-satisfaction guarantee. If you are not content, we take them back without any question.</p>

  </div> <!-- end  column-->

  <div class = "col-sm-12 col-md-4">
    <div class = "my-badge-ani" id = "featuredBadge">Featured products</div>

    <div id = "myProductCarousel" class="carousel slide carousel-fade" data-ride="carousel" data-interval="4000">

      <!-- Indicators -->
      <ol class="carousel-indicators">
        <% for ii in 0..@products.length-1%>
        <li data-target="#myProductCarousel" data-slide-to= "<%=ii%>" <%= "class = active" if ii == 0  %>></li>
        <%end%>
      </ol>

     <!-- Cards -->
      <div class="carousel-inner">
        <% @products.each do |product| %>
        <div class="carousel-item<%= " active" if product == @products.first %>">
          <%= render partial: 'shared/product', object: product, locals: {includeButtons: false} %>
        </div>
        <% end %>
      </div>

    </div> <!-- end  myProductCarousel-->
  </div> <!-- end  column-->
</div> <!-- end  row-->

app/views/simple_pages/thank_you.html.erb
  <div class="my-received">
    <div class = "my-received__message">
      <h3>Thank you! We have received your message and will respond as soon as possible.</h3>
    </div>
  </div>