config/routes.rb
Rails.application.routes.draw do
  # simplify devise path names and change sign_in/sign_out to login/logout
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  resources :products do
    resources :comments
  end
  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  post 'simple_pages/thank_you'
  post 'payments/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'simple_pages#landing_page'

  mount ActionCable.server => '/cable'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # Devise require authentication
  before_action :authenticate_user!

  # CanCanCan helper
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    if current_user.admin?
      @users = User.all
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    if current_user.admin?
      @user = User.new
    else
      redirect_to root_path, notice: "That's no place for you!"
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(user_params)
    @user.confirmed_at = DateTime.now # to prevent email confirmation

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }

        # Tell the UserMailer to send a welcome email after save
        # UserMailer.with(user: @user).welcome_mail.deliver_now
        # format.html { redirect_to(@user, notice: 'User was successfully created.') }
        # format.json { render json: @user, status: :created, location: @user }

      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update_with_password(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      if current_user.admin?
        format.html { redirect_to users_path, notice: 'User was successfully destroyed.' }
      else
        format.html { redirect_to root_path, notice: 'Hope to see again, bye bye!' }
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
<% if user.errors.any? %>

<div class = "my-error-explanation">
<p><%=fa_stacked_icon "exclamation-triangle", base: "square-o"%>
<%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</p>

  <ul>
    <% user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<form>
  <div class="row">
    <div class="col-md-6 form-group">
      <%= form.label :first_name, class: "control-label" %>
      <%= form.text_field :first_name , class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 form-group">
      <%= form.label :last_name, class: "control-label" %>
      <%= form.text_field :last_name, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 form-group">
      <%= form.label :email, class: "control-label" %>
      <%#= form.text_field :email, class: "form-control", disabled: true %>
      <%= form.text_field :email, class: "form-control"%>

    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-6">
      <%= form.label :password %>

      <%if change_password%>
      <i>(leave blank if you don't want to change it)</i><br />
      <%end%>

      <%= form.password_field :password, autocomplete: "off", class: "form-control" %>
      <% if @minimum_password_length %>
      <em><%= @minimum_password_length %> characters minimum</em>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-6">
      <%= form.label :password_confirmation%>
      <%= form.password_field :password_confirmation, autocomplete: "off" , class: "form-control"%>
    </div>
  </div>

<%if change_password%>
  <div class="row">
    <div class="form-group col-md-6">
      <%= form.label :current_password %> <i>(we need your current password to confirm your changes)</i>
      <%= form.password_field :current_password, autocomplete: "off" , class: "form-control"%>
    </div>
  </div>
<%end%>

  <div class="row">
    <%= form.submit "Submit changes", class: "btn btn-light my-form-submit-button" %>
  </div>

</form>

  <div class="col-md-6 my-delete-account">
    <h2>Delete account</h3>
    <p>Unhappy? You can delete your account by clicking the button below. <em>This action cannot be undone!</em>
    <%= button_to "Delete my account", user, data: { confirm: "Are you sure?" }, method: :delete , class: "btn btn-danger mr-auto"%></p>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user, change_password: true %>

<div class = "my-nav-buttons">
  <%= link_to 'Back', user_path(current_user), class: "btn-sm btn-light" %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="my-table" id = "myUsersTable">

  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.email %></td>
    <td> <% if user.admin %>
           <%= 'Yes' %>
         <% end %>
    </td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
</tbody>

</table>
<% if current_user.admin? %>
  <%= link_to('New User', new_user_path, :class => "btn btn-light", :id =>"myNewUserBtn") %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render 'form', user: @user, change_password: false %>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>Your account info</h1>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Orders:</strong>
  <%#= @user.orders[0].product.name %>

<% orders = @user.orders%>
  <%if orders.present?%>
    <ol class="list-group" id = "myUserOrdersList">
      <% orders.each_with_index do |order, index|%>
        <li class="list-group-item my-orders-list"><%= link_to(orders[index].product.name, order_path(order))%></li>
      <%end%>
    </ol>
  <%end%>
</p>

<div class = "my-nav-buttons">
  <%= link_to fa_icon("edit")+" Edit", edit_user_path(@user), class: "btn-sm btn-light" %>
</div>