config/routes.rb
Rails.application.routes.draw do
  # simplify devise path names and change sign_in/sign_out to login/logout
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  resources :products do
    resources :comments
  end
  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  post 'simple_pages/thank_you'
  post 'payments/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'simple_pages#landing_page'

  mount ActionCable.server => '/cable'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pirx on Rails</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body class = "my-bg-img">

  <nav class="navbar navbar-expand-lg navbar-light bg-light" id = "myNavBar">
    <%= link_to "The Cobweb Company", root_path, :class => "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <li><%= link_to "Products", products_path, :class => "nav-link" %></li>
        </li>
        <li class="nav-item">
          <li><%= link_to "About", simple_pages_about_path, :class => "nav-link" %></li>
        </li>
        <li class="nav-item">
          <li><%= link_to "Contact", simple_pages_contact_path, :class => "nav-link" %></li>
        </li>

        <li class="nav-item d-flex align-items-center" data-toggle ="tooltip" data-placement="right" title = "Search products">

          <%= form_with(url: products_path, method: 'get', local: true, class: "d-flex my-search-form") do |form| %>
            <%= form.text_field :q, id: 'q', value: params[:q], class: "form-control" %>
            <%= button_tag type: 'submit', class: "btn my-btn my-btn--small nav-link d-flex", id: "mySearchBtn" do %>
              <i class="fa fa-search" aria-hidden="true"></i>
            <% end %>
          <% end %>
        </li>

      </ul>

      <ul class="navbar-nav pull-right">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to fa_icon("wrench"), user_path(current_user), :class => "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to('Logout', destroy_user_session_path, method: :delete, :class => "nav-link") %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to('Login', new_user_session_path, :class => "nav-link") %>
        </li>

        <% end %>
      </li>
      </ul>

    </div>
  </nav>

  <!-- <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p> -->

  <% flash.each do |key, value| %>
    <div class="alert alert-warning alert-<%= key %>"><%= value %></div>
  <% end %>


  <div class = "my-main-content">
    <%= yield %>
  </div>

  <footer>
    <div class = "my-footer">
      &copy; 2018 Peter Pirx
    </div>
  </footer>

</body>
</html>

app/views/layouts/landing_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pirx on Rails landing</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>

  <%= yield %>

</body>
</html>